rconsolename("Galaxy Hub - Arsenal - Fluxus")
rconsoleprint("[1/3] Validating User \n")
wait(2)
rconsoleprint("[2/3] Loading Galaxy \n")
wait(3)
loadstring(game:HttpGet("https://raw.githubusercontent.com/SkyGodCheesey/Galaxy-Hub/main/Arsenal.lua", true))()
rconsoleprint("[3/3] Loaded, enjoy galaxy! (Minimize this")
wait(5) 
rconsoleclear()
