rconsolename("Galaxy Hub | Tower Of Hell")
rconsoleprint("[1/3] Validating User \n")
wait(1)
rconsoleprint("[2/3] Loading Galaxy \n")
wait(0.5)
loadstring(game:HttpGet("https://raw.githubusercontent.com/SkyGodCheesey/Galaxy-Hub/main/TOH.lua", true))()
rconsoleprint("[3/3] Loaded, enjoy galaxy! (Minimize this")
wait(5) 
rconsoleclear()
